version: "3.9"

services:
  app:
    build: .
    container_name: aesop-app
    ports:
      - "8091:8091"
    depends_on:
      - db
      - redis
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/aesop
      SPRING_DATASOURCE_USERNAME: beyond
      SPRING_DATASOURCE_PASSWORD: beyond
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  db:
    image: mariadb
    container_name: aesop-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: beyond
      MARIADB_USER: beyond
      MARIADB_PASSWORD: beyond
      MARIADB_DATABASE: aesop
    ports:
      - "3307:3306"

  redis:
    image: redis
    container_name: aesop-redis
    restart: always
    # ports:
    #   - "6379:6379"
